liquidity_sweep_config:
  detection_params:
    min_price_move_bps: 10  # basis points
    max_time_window_ms: 500
    min_volume_multiplier: 2.5
    directional_consistency: 0.8
  sweep_types:
    - stop_hunt
    - liquidity_grab
    - momentum_ignition