# docker-compose.override.yml
# Add this to your docker-compose to include the tick-to-bar service


services:
  tick-to-bar:
    build:
      context: .
      dockerfile: Dockerfile.tick-to-bar
    container_name: tick-to-bar
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SYMBOLS=EURUSD,GBPUSD,USDJPY,XAUUSD
      - LOG_LEVEL=INFO
    depends_on:
      - redis
      - mt5
    networks:
      - default
    restart: unless-stopped
    volumes:
      - ./tick_to_bar.py:/app/tick_to_bar.py
    command: python /app/tick_to_bar.py
