version: "3.9"

services:
  kafka:
    image: vectorized/redpanda:v23.1.11
    command:
      - redpanda start
      - --smp 1
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      - --advertise-kafka-addr PLAINTEXT://kafka:9092,OUTSIDE://localhost:29092
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster info --brokers=localhost:29092 >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10

volumes:
  redpanda-data:

# Usage:
#   docker compose -f docker-compose.yml -f docker-compose.kafka.yml up -d
