version: "3.9"
services:
  pulse-api:
    build:
      context: .
      dockerfile: Dockerfile.pulse-api
    environment:
      HOST: 0.0.0.0
      PORT: 8000
      PULSE_CONFIG: /srv/pulse-api/pulse_config.yaml
      PULSE_CORS_ORIGINS: "http://localhost:8501,http://127.0.0.1:8501,*"
      LOG_LEVEL: INFO
      RELOAD: "0"
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks: [pulse-net]

  streamlit:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - .:/app
    command: bash -lc "pip install -r requirements.txt && streamlit run pulse_ui_enhanced.py --server.port 8501 --server.address 0.0.0.0"
    environment:
      PULSE_API_BASE: "http://pulse-api:8000"
    ports:
      - "8501:8501"
    depends_on:
      - pulse-api
    networks: [pulse-net]

  redis:
    image: redis:7.2-alpine
    ports: ["6379:6379"]
    networks: [pulse-net]

networks:
  pulse-net: {}
