# Zanalytics Pulse Production Configuration
pulse:
  version: "v11.5.1"
  environment: "production"

# Risk Management (Conservative for Prop Firm)
risk_management:
  daily_loss_limit: 0.03  # 3% buffer under 5% prop limit
  warning_threshold: 0.02  # 2% warning level
  
  risk_phases:
    low_equity:
      per_trade_risk: 0.005  # 0.5%
      max_trades_per_day: 3
      description: "Conservative phase - building confidence"
      
    stable:
      per_trade_risk: 0.0075  # 0.75%
      max_trades_per_day: 4
      description: "Stable phase - moderate risk"
      
    new_high:
      per_trade_risk: 0.01  # 1.0%
      max_trades_per_day: 5
      description: "Growth phase - optimal risk"
      
    recovery:
      per_trade_risk: 0.005  # 0.5%
      max_trades_per_day: 3
      description: "Recovery phase - risk reduction"

# Behavioral Safeguards (Trading in the Zone Integration)
behavioral_safeguards:
  overconfidence_protection:
    rapid_trading_threshold: 5  # minutes between trades
    consecutive_wins_limit: 3
    size_reduction_factor: 0.8
    
  revenge_trading_prevention:
    consecutive_loss_limit: 2
    cooldown_minutes: 15
    detection_window_minutes: 30
    
  disposition_effect_mitigation:
    min_risk_reward: 1.5
    auto_exit_rules: true
    loss_limit_enforcement: "strict"
    
  loss_aversion_management:
    drawdown_pause_threshold: 0.025  # 2.5%
    recovery_requirement: "new_equity_high"
    max_consecutive_losses: 2

# Confluence Scoring
confluence_scoring:
  weights:
    smc: 0.35
    wyckoff: 0.35
    technical: 0.20
    midas: 0.10
    
  thresholds:
    low: 40
    medium: 60
    high: 80
    
  minimum_factors: 2

# Performance Targets
performance_targets:
  daily_loss_frequency: 0.10    # <10%
  rule_adherence: 0.95          # >95%
  ui_response_time: 2.0         # <2s
  decision_latency: 0.1         # <100ms
  risk_efficiency: 0.75         # >75%

# Integration Settings
integration:
  django_api:
    base_url: "${DJANGO_API_URL:-http://django:8000}"
    timeout: 2.0
    
  redis:
    host: "${REDIS_HOST:-redis}"
    port: "${REDIS_PORT:-6379}"
    cache_ttl: 300
    
  mt5_api:
    login: "${MT5_LOGIN:-}"
    password: "${MT5_PASSWORD:-}"
    server: "${MT5_SERVER:-}"

# Logging and Monitoring
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
monitoring:
  health_check_interval: 30
  alert_thresholds:
    api_latency: 1000  # ms
    memory_usage: 80   # percent
    
# Dashboard Configuration
dashboard:
  refresh_interval: 5  # seconds
  max_recent_decisions: 20
  auto_refresh: false
  
  tiles:
    - confluence_score
    - market_bias
    - risk_remaining
    - suggested_rr
    - top_opportunities
    - behavioral_insights
