weights:
  smc: 0.33
  wyckoff: 0.34
  technical: 0.33
wyckoff:
  window: 50
  scorer_weights:
    w_phase: 0.55
    w_events: 0.20
    w_vsa: 0.25
  guard:
    vol_gate: 1.2
    eff_gate: 0.8
  confirm:
    spring:
      fwd_window: 10
      vol_z_min: 0.5
      fwd_ret_min: 0.002
    upthrust:
      fwd_window: 10
      vol_z_min: 0.5
      fwd_ret_min: 0.002
  news_buffer:
    enabled: true
    pre_bars: 2
    post_bars: 2
    volz_thresh: 3.0
    clamp: 0.6
