version: '3'

services:
  mcp2:
    image: mcp2:latest
    depends_on:
      - postgres
      - redis
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      MCP_API_KEY: ${MCP_API_KEY}
    ports:
      - "8002:8002"
    volumes:
      - mcp2-data:/app/data
    networks:
      - mcp2-network

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    networks:
      - mcp2-network

  postgres:
    image: postgres:15-alpine
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mcp2-network

volumes:
  mcp2-data:
  redis-data:
  postgres-data:

networks:
  mcp2-network:
    driver: bridge
