# Ordered list of enrichment processors with per-processor settings
processors:
  - module: services.enrichment.modules.harmonic_processor
    enabled: true
    settings:
      upload: false
  - module: services.enrichment.modules.context_analyzer
    enabled: false
    settings: {}
  - module: utils.enrichment.smc
    enabled: false
    settings: {}
  - module: utils.enrichment.poi
    enabled: false
    settings: {}
  - module: utils.enrichment.dss
    enabled: false
    settings: {}
  - module: utils.enrichment.rsi
    enabled: false
    settings:
      period: 14
      column: close
