# Default enrichment configuration grouped by category.
# These examples demonstrate the expected schema.

core:
  structure_validator: true

technical:
  groups:
    momentum:
      enabled: true
      indicators:
        rsi: true
        macd: true
    volatility:
      enabled: true
      indicators:
        atr: true
        bollinger: true

structure:
  smc: true
  wyckoff: true

advanced:
  liquidity_engine: true
  context_analyzer: true
  fvg_locator: true
  predictive_scorer: true
  fractal_detector: true
  fractal_bars: 2
  smc: false
  poi: false
  divergence: false
  rsi_fusion: false
  harmonic:
    enabled: true
    collection: harmonic_patterns
    upload: true
  alligator:
    enabled: true
    jaw: 13
    teeth: 8
    lips: 5

vector_db:
  collection: enrichment_vectors

embedding:
  model: text-embedding-3-small
