# YFinance backup feed configuration
#
# This file controls the redundant Yahoo Finance bars endpoint
# exposed at /api/v1/feed/yf-bars. Environment variables override
# values in this file at runtime.
#
# Env overrides (examples):
#   YF_ENABLED=true
#   YF_DEFAULT_INTERVAL=1h
#   YF_DEFAULT_RANGE=60d
#   YF_MAX_POINTS=1500
#   YF_PROXY=http://proxy.local:8080

enabled: true

defaults:
  interval: "1h"     # 1m, 2m, 5m, 15m, 30m, 1h, 1d
  range: "60d"       # 5d, 30d, 60d, 1y, etc.
  max_points: 1500    # server-side cap to keep payload size reasonable

network:
  proxy: null         # e.g., "http://proxy.local:8080" or null

limits:
  allowed_intervals: ["1m", "2m", "5m", "15m", "30m", "1h", "1d"]
  allowed_ranges: ["5d", "30d", "60d", "90d", "6mo", "1y", "2y"]

