name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Validate requirement references
        run: python scripts/validate_requirements.py
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -c constraints.txt
          pip install .[lint]
      - name: Lint docstrings
        run: make lint-docs
      - name: Validate action routes
        run: python scripts/validate_actions.py
      - name: Run pytest
        run: pytest -m "not mt5" -q

