name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -c constraints.txt
          pip install .[lint]
      - name: Install hadolint
        run: |
          wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x /usr/local/bin/hadolint
      - name: Lint Dockerfiles
        run: hadolint $(git ls-files '*Dockerfile*')
      - name: Validate requirement paths
        run: python scripts/validate_requirement_paths.py
      - name: Lint docstrings
        run: make lint-docs
      - name: Validate action routes
        run: python scripts/validate_actions.py
      - name: Run pytest
        run: pytest -m "not mt5" -q

