name: Weekly Wyckoff Weight Calibration

on:
  schedule:
    # Runs every Sunday at 05:00 UTC
    - cron: '0 5 * * 0'
  workflow_dispatch: # Allows manual triggering for on-demand calibration

jobs:
  calibrate-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 3. Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyyaml

      - name: 4. Prepare Labeled Data
        run: |
          # IMPLEMENTATION NOTE: Replace this with your actual script to pull labeled data
          # Example: python scripts/pull_labeled_data.py --output data/labeled_playback.pkl
          echo "Placeholder for data preparation script."
          mkdir -p data && touch data/labeled_playback.pkl

      - name: 5. Run Calibration Script
        id: calibration
        run: |
          # This script executes the grid search and outputs the best weights as a JSON string.
          # It includes a performance improvement guardrail.
          BEST_METRICS_JSON=$(python .github/scripts/run_calibration_with_guard.py \
            --config-path pulse_config.yaml \
            --data-path data/labeled_playback.pkl \
            --min-improvement 0.05) # Require a 5% improvement to commit
          echo "NEW_WEIGHTS=$BEST_METRICS_JSON" >> $GITHUB_ENV

      - name: 6. Update Config File (if new weights are found)
        if: env.NEW_WEIGHTS != '{}'
        run: |
          python .github/scripts/update_wyckoff_weights.py \
            --config-path pulse_config.yaml \
            --weights '${{ env.NEW_WEIGHTS }}'

      - name: 7. Commit Updated Weights (if changed)
        if: env.NEW_WEIGHTS != '{}'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci(wyckoff): auto-calibrate model weights"
          branch: main
          file_pattern: 'pulse_config.yaml'
          commit_user_name: 'Zanalytics CI Bot'
          commit_user_email: 'ci-bot@zanalytics.ai'
