name: Weekly Wyckoff Calibration
on:
  schedule: [{ cron: "0 3 * * 0" }]
  workflow_dispatch: {}
jobs:
  calibrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python .github/scripts/run_calibration_with_guard.py
      - name: Create PR if changed
        uses: peter-evans/create-pull-request@v6
        with:
          title: "chore: weekly wyckoff weights calibration"
          commit-message: "chore: update wyckoff weights (auto)"
          branch: "auto/calibrate-wyckoff"
          base: "main"
          labels: "calibration,auto"

